filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - "/var/log/partya/node-*"
    - "/var/log/partyb/node-*"
    - "/var/log/notary/node-*"
output.logstash:
    hosts: ["elk:5044"]
