---
- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose

- name: change permission for docker-compose
  file:
    path: /usr/local/bin/docker-compose
    mode: 0777

- name: Map docker hostname to localhost
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1"
    state: present
...